- hosts: targets
  become: yes
  tasks:
    - name: Disable root login over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        backup: yes
    - name: Enforce SSH protocol 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Protocol"
        line: "Protocol 2"
        backup: yes
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
